env:
  es2017: true
  browser: true
  commonjs: true

extends: [
  'plugin:react/recommended',
  'react-app',
  'prettier'
  ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: [
  'react',
  'prettier'
  ]

settings:
  react:
    version: '16'
